<?xml version="1.0"?>
<robot name="robot" xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:include filename="$(find robot_description)/urdf/gazebo.urdf.xacro" />


    <!-- Define robot constants -->

    <!-- Values order for is: length, width, height -->

    <!-- Boat -->
    <xacro:property name="bottom_size" value="0.48 0.32 0.04"/>
    <xacro:property name="bottom_x" value="0.48"/>
    <xacro:property name="bottom_y" value="0.32"/>
    <xacro:property name="bottom_z" value="0.04"/>
    
    <xacro:property name="long_side_size" value="0.48 0.03 0.12"/>
    <xacro:property name="long_side_x" value="0.48"/>
    <xacro:property name="long_side_y" value="0.03"/>
    <xacro:property name="long_side_z" value="0.12"/>

    <xacro:property name="short_side_size" value="0.03 0.32 0.12"/>
    <xacro:property name="short_side_x" value="0.03"/>
    <xacro:property name="short_side_y" value="0.32"/>
    <xacro:property name="short_side_z" value="0.12"/>

    <!-- Paddles -->
    <xacro:property name="paddle_handle_size" value="0.02 0.04 0.32"/>
    <xacro:property name="paddle_handle_x" value="0.02"/>
    <xacro:property name="paddle_handle_y" value="0.04"/>
    <xacro:property name="paddle_handle_z" value="0.32"/>

    <xacro:property name="paddle_plate_size" value="0.02 0.10 0.14"/>
    <xacro:property name="paddle_plate_x" value="0.02"/>
    <xacro:property name="paddle_plate_y" value="0.10"/>
    <xacro:property name="paddle_plate_z" value="0.14"/>

    <!-- Pig -->
    <xacro:property name="body_size" value="0.32 0.20 0.16"/>
    <xacro:property name="body_x" value="0.32"/>
    <xacro:property name="body_y" value="0.20"/>
    <xacro:property name="body_z" value="0.16"/>

    <xacro:property name="leg_size" value="0.08 0.08 0.12"/>
    <xacro:property name="leg_x" value="0.08"/>
    <xacro:property name="leg_y" value="0.08"/>
    <xacro:property name="leg_z" value="0.12"/>

    <xacro:property name="head_size" value="0.16 0.16 0.16"/>
    <xacro:property name="head_x" value="0.16"/>
    <xacro:property name="head_y" value="0.16"/>
    <xacro:property name="head_z" value="0.16"/>

    <xacro:property name="nose_size" value="0.02 0.08 0.06"/>
    <xacro:property name="nose_x" value="0.02"/>
    <xacro:property name="nose_y" value="0.08"/>
    <xacro:property name="nose_z" value="0.06"/>

    <xacro:property name="square_size" value="0.0001 0.02 0.02"/>

    <!-- Wheels -->
    <xacro:property name="wheel_radius" value="0.08"/>
    <xacro:property name="wheel_width" value="0.03"/>

    <!-- Mass -->
    <xacro:property name="boat_mass" value="1"/>
    <xacro:property name="pig_mass" value="0.5"/>
    <xacro:property name="wheel_mass" value="0.1"/>
    <xacro:property name="caster_wheel_mass" value="0.005"/>

    <!-- ~~~~~~~~~~~~~~~ -->
    <!-- INERTIAL MACROS -->
    <!-- ~~~~~~~~~~~~~~~ -->

    <!-- Values order is width, height, depth -->
    <xacro:macro name="box_inertia" params="m x y z xyz rpy">
        <inertial>
            <!-- <origin xyz="${xyz}" rpy="${rpy}"/> -->
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${m}"/>
            <inertia ixx="${(m/12) * (z*z + y*y)}" ixy="0.0" ixz="0.0" iyy="${(m/12) * (x*x + y*y)}" iyz="0.0" izz="${(m/12) * (x*x + z*z)}"/>
            <!-- <inertia ixx="${(m/12) * (size[2]*size[2] + size[0]*size[0])}" ixy="0.0" ixz="0.0" iyy="${(m/12) * (size[1]*size[1] + size[0]*size[0])}" iyz="0.0" izz="${(m/12) * (size[1]*size[1] + size[2]*size[2])}"/> -->
        </inertial>
    </xacro:macro>

    <xacro:macro name="cylinder_inertia" params="m r h xyz rpy">
        <inertial>
            <!-- <origin xyz="${xyz}" rpy="${rpy}" /> -->
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${m}"/>
            <inertia ixx="${(m/12) * (3*r*r + h*h)}" ixy = "0" ixz = "0" iyy="${(m/12) * (3*r*r + h*h)}" iyz = "0" izz="${(m/2) * (r*r)}"/>
        </inertial>
    </xacro:macro>

    <xacro:macro name="sphere_inertia" params="m r xyz rpy">
        <inertial>
            <!-- <origin xyz="${xyz}" rpy="${rpy}" /> -->
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${m}"/>
            <inertia ixx="${(2/5) * m * (r*r)}" ixy="0.0" ixz="0.0" iyy="${(2/5) * m * (r*r)}" iyz="0.0" izz="${(2/5) * m * (r*r)}"/>
        </inertial>
    </xacro:macro>
    
    <!-- ~~~~~ -->
    <!-- LINKS -->
    <!-- ~~~~~ -->

    <!-- LIMIT CYLINDER -->

    <!-- <link name="cylinder">
        <visual>
            <geometry>
                <cylinder radius="1.05" length="2.5"/>
            </geometry>
            <material name="Wood">
                <color rgba="0.58 0.46 0.18 0.3"/>
            </material>
        </visual>
    </link> -->

    <!-- BOAT -->
    <link name="bottom_link">
        <visual>
            <geometry>
                <box size="${bottom_size}"/>
            </geometry>
            <material name="Wood">
                <color rgba="0.58 0.46 0.18 1.0"/>
            </material>
        </visual>
        
        <collision>
            <geometry>
                <box size="${bottom_size}"/>
            </geometry>
        </collision>

        <xacro:box_inertia m="${boat_mass}" x="${bottom_x}" y="${bottom_y}" z="${bottom_z}" xyz="0 0 0" rpy="0 0 0" />
    </link>


    <xacro:macro name="shared_side_link" params="name mass_coef size x y z xyz rpy">
        <link name="${name}">
            <visual>
                <geometry>
                    <box size="${size}"/>
                </geometry>
                <material name="Wood">
                    <color rgba="0.58 0.46 0.18 1.0"/>
                </material>
            </visual>
            
            <collision>
                <geometry>
                    <box size="${size}"/>
                </geometry>
            </collision>

            <xacro:box_inertia m="${boat_mass*mass_coef}" x="${x}" y="${y}" z="${z}" xyz="0 0 0" rpy="0 0 0" />
        </link>

        <joint name="${name}_joint" type="fixed">
            <parent link="bottom_link" />
            <child link="${name}" />
            <origin xyz="${xyz}" rpy="${rpy}" />
        </joint>
    </xacro:macro>


    <xacro:macro name="shared_paddle_link" params="name plate_name parent_name xyz rpy">
        <link name="${name}">
            <visual>
                <geometry>
                    <box size="${paddle_handle_size}"/>
                </geometry>
                <material name="Wood">
                    <color rgba="0.52 0.42 0.18 1.0"/>
                </material>
            </visual>

            <!-- <collision>
                <geometry>
                    <box size="${paddle_handle_size}"/>
                </geometry>
            </collision>

            <xacro:box_inertia m="${boat_mass*0.05}" x="${paddle_handle_x}" y="${paddle_handle_y}" z="${paddle_handle_z}" xyz="${xyz}" rpy="${rpy}" /> -->
        </link>

        <link name="${plate_name}">
            <visual>
                <geometry>
                    <box size="${paddle_plate_size}"/>
                </geometry>
                <material name="Wood">
                    <color rgba="0.46 0.36 0.10 1.0"/>
                </material>
            </visual>

            <!-- <collision>
                <geometry>
                    <box size="${paddle_plate_size}"/>
                </geometry>
            </collision>

            <xacro:box_inertia m="${boat_mass*0.1}" x="${paddle_plate_x}" y="${paddle_plate_y}" z="${paddle_plate_z}" xyz="0.02 0 0.14" rpy="0 0 0" /> -->
        </link>

        <joint name="${plate_name}_joint" type="fixed">
            <parent link="${name}" />
            <child link="${plate_name}" />
            <origin xyz="0.02 0 0.14" rpy="0 0 0" />
        </joint>

        <joint name="${name}_joint" type="fixed">
            <parent link="${parent_name}" />
            <child link="${name}" />
            <origin xyz="${xyz}" rpy="${rpy}" />
        </joint>
    </xacro:macro>


    <!-- PIG -->

    <link name="body_link">
        <visual>
            <geometry>
                <box size="${body_size}"/>
            </geometry>
            <material name="Pink">
                <color rgba="0.88 0.26 0.26 1.0"/>
            </material>
        </visual>
        
        <collision>
            <geometry>
                <box size="${body_size}"/>
            </geometry>
        </collision>

        <xacro:box_inertia m="${pig_mass}" x="${body_x}" y="${body_y}" z="${body_z}" xyz="0.02 0 0.20" rpy="0 0 0" />
    </link>


    <link name="head_link">
        <visual>
            <geometry>
                <box size="${head_size}"/>
            </geometry>
            <material name="Pink">
                <color rgba="0.859 0.318 0.318 1.0"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <box size="${head_size}"/>
            </geometry>
        </collision>

        <xacro:box_inertia m="${pig_mass/3}" x="${head_x}" y="${head_y}" z="${head_z}" xyz="0.20 0 0.04" rpy="0 0 0" />
    </link>


    <link name="nose_link">
        <visual>
            <geometry>
                <box size="${nose_size}"/>
            </geometry>
            <material name="Pink">
                <color rgba="0.75 0.20 0.20 1.0"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <box size="${nose_size}"/>
            </geometry>
        </collision>

        <xacro:box_inertia m="${pig_mass/10}" x="${nose_x}" y="${nose_y}" z="${nose_z}" xyz="0.09 0 -0.03" rpy="0 0 0" />
    </link>


    <xacro:macro name="shared_leg_link" params="name xyz rpy">
        <link name="${name}">
            <visual>
                <geometry>
                    <box size="${leg_size}"/>
                </geometry>
                <material name="Pink">
                    <color rgba="0.859 0.318 0.318 1.0"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <box size="${leg_size}"/>
                </geometry>
            </collision>

            <xacro:box_inertia m="${pig_mass/4}" x="${leg_x}" y="${leg_y}" z="${leg_z}" xyz="${xyz}" rpy="${rpy}" />
        </link>

        <joint name="${name}_joint" type="fixed">
            <parent link="body_link" />
            <child link="${name}" />
            <origin xyz="${xyz}" rpy="${rpy}" />
        </joint>        
    </xacro:macro>


    <xacro:macro name="shared_square_link" params="name xyz rpy color_name color">
        <link name="${name}">
            <visual>
                <geometry>
                    <box size="${square_size}"/>
                </geometry>
                <material name="${color_name}">
                    <color rgba="${color}"/>
                </material>
            </visual>
        </link>
        
        <joint name="${name}_joint" type="fixed">
            <parent link="head_link" />
            <child link="${name}" />
            <origin xyz="${xyz}" rpy="${rpy}" />
        </joint>
    </xacro:macro>

    <!-- Caster wheel -->

    <!-- <link name="plate">
        <visual>
            <geometry>
                <box size="10 10 0.0001"/>
            </geometry>
            <material name="Red">
                <color rgba="1 0 0 0.3"/>
            </material>
        </visual>
    </link>

    <joint name="plate_joint" type="fixed">
            <parent link="bottom_link" />
            <child link="plate" />
            <origin xyz="0 0 -${wheel_radius}" rpy="0 0 0" />
    </joint> -->

    <link name="base_footprint" />

    <joint name="footprint_joint" type="fixed">
        <parent link="bottom_link"/>
        <child link="base_footprint"/>
        <origin xyz="0.0 0.0 ${-(wheel_radius)}" rpy="0 0 0"/>
    </joint>

    <link name="caster_wheel_link">
        <visual>
            <geometry>
                <!-- <sphere radius="${wheel_radius/2.8}" /> -->
                <sphere radius="${wheel_radius/4}" />
            </geometry>
            <material name="Dark Wood">
                <color rgba="0.46 0.36 0.10 1.0"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <!-- <sphere radius="${wheel_radius/2.8}" /> -->
                <sphere radius="${wheel_radius/4}" />
            </geometry>
        </collision>

        <!-- <xacro:sphere_inertia m="${caster_wheel_mass}" r="${wheel_radius/2.8}" xyz="-0.16 0 -0.051" rpy="0 0 0"/> -->
        <xacro:sphere_inertia m="${caster_wheel_mass}" r="${wheel_radius/4}" xyz="-0.16 0 -0.06" rpy="0 0 0"/>
    </link>

    <!-- HELPER -->
    <link name="caster_cylinder_link">
        <visual>
            <geometry>
                <cylinder radius="0.01" length="0.1"/>
            </geometry>
            <material name="Red">
                <color rgba="1 0 0 1.0"/>
            </material>                
        </visual>
    </link>

    <joint name="caster_cylinider_joint" type="fixed">
        <parent link="caster_wheel_link" />
        <child link="caster_cylinder_link" />
        <origin xyz="0.1 0 0" rpy="0 ${pi/2} 0" />
    </joint>
    <!-- HELPER -->

    <!-- <joint name="caster_wheel_joint" type="continuous">
        <parent link="bottom_link" />
        <child link="caster_wheel_link" />
        <origin xyz="-0.16 0 -0.051" rpy="0 0 0" />
        <origin xyz="-0.16 0 -0.06" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint> -->

    <joint name="caster_wheel_joint" type="fixed">
        <parent link="bottom_link" />
        <child link="caster_wheel_link" />
        <!-- <origin xyz="-0.16 0 -0.051" rpy="0 0 0" /> -->
        <origin xyz="-0.16 0 -0.06" rpy="0 0 0" />
    </joint>

    <!-- Wheels -->

    <xacro:macro name="shared_wheel_link" params="name x_angle xyz">
        <link name="${name}_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
                <material name="Dark Wood">
                    <color rgba="0.46 0.36 0.10 1.0"/>
                </material>                
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
            </collision>

            <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}" xyz="${xyz}" rpy="${x_angle} 0 0" />
        </link>

        <!-- HELPER -->
        <link name="${name}_cylinder_link">
            <visual>
                <geometry>
                    <cylinder radius="0.01" length="0.1"/>
                </geometry>
                <material name="Red">
                    <color rgba="1 0 0 1.0"/>
                </material>                
            </visual>
        </link>

        <joint name="${name}_cylinider_joint" type="fixed">
            <parent link="${name}_link" />
            <child link="${name}_cylinder_link" />
            <origin xyz="0.1 0 0" rpy="0 ${pi/2} 0" />
        </joint>
        <!-- HELPER -->

        <joint name="${name}_joint" type="continuous">
            <parent link="bottom_link" />
            <child link="${name}_link" />
            <origin xyz="${xyz}" rpy="${x_angle} 0 0" />
            <axis xyz="0 0 ${-x_angle/(pi/2)}" />
            <!-- <axis xyz="0 0 1" /> -->
        </joint>
    </xacro:macro>


    <!-- ~~~~~~ -->
    <!-- JOINTS -->
    <!-- ~~~~~~ -->
    <joint name="pig_joint" type="fixed">
        <parent link="bottom_link" />
        <child link="body_link" />
        <!-- <origin xyz="0.02 0 0.20" rpy="0 0 0" /> -->
        <origin xyz="-0.02 0 0.20" rpy="0 0 0" />
    </joint>

    <joint name="head_joint" type="fixed">
        <parent link="body_link" />
        <child link="head_link" />
        <origin xyz="0.20 0 0.04" rpy="0 0 0" />
    </joint>

    <joint name="nose_joint" type="fixed">
        <parent link="head_link" />
        <child link="nose_link" />
        <origin xyz="0.09 0 -0.03" rpy="0 0 0" />
    </joint>

    <xacro:shared_leg_link name="front_right_leg" xyz="0.1 -0.06 -0.14" rpy="0 0 0" />
    <xacro:shared_leg_link name="front_left_leg" xyz="0.1 0.06 -0.14" rpy="0 0 0" />
    <xacro:shared_leg_link name="back_right_leg" xyz="-0.14 -0.06 -0.14" rpy="0 0 0" />
    <xacro:shared_leg_link name="back_left_leg" xyz="-0.14 0.06 -0.14" rpy="0 0 0" />

    <xacro:shared_square_link name="left_pupil" xyz="0.0801 -0.07 0.01" rpy="0 0 0" color_name="Black" color="0 0 0 1" />
    <xacro:shared_square_link name="right_pupil" xyz="0.0801 0.07 0.01" rpy="0 0 0" color_name="Black" color="0 0 0 1" />
    <xacro:shared_square_link name="left_eyeball" xyz="0.0801 -0.05 0.01" rpy="0 0 0" color_name="White" color="1 1 1 1" />
    <xacro:shared_square_link name="right_eyeball" xyz="0.0801 0.05 0.01" rpy="0 0 0" color_name="White" color="1 1 1 1" />

    <xacro:shared_square_link name="left_nostril" xyz="0.1001 -0.03 -0.03" rpy="0 0 0" color_name="Brown" color="0.4 0.08 0.07 1" />
    <xacro:shared_square_link name="right_nostril" xyz="0.1001 0.03 -0.03" rpy="0 0 0" color_name="Brown" color="0.4 0.08 0.07 1" />

    <xacro:shared_side_link name="right_side" size="${long_side_size}" mass_coef="0.4" x="${long_side_x}" y="${long_side_y}" z="${long_side_z}" xyz="0 -0.175 0.07" rpy="0 0 0" />
    <xacro:shared_side_link name="left_side" size="${long_side_size}" mass_coef="0.4" x="${long_side_x}" y="${long_side_y}" z="${long_side_z}" xyz="0 0.175 0.07" rpy="0 0 0" />
    <xacro:shared_side_link name="front_side" size="${short_side_size}" mass_coef="0.2" x="${short_side_x}" y="${short_side_y}" z="${short_side_z}" xyz="0.255 0 0.07" rpy="0 0 0" />
    <xacro:shared_side_link name="back_side" size="${short_side_size}" mass_coef="0.2" x="${short_side_x}" y="${short_side_y}" z="${short_side_z}" xyz="-0.255 0 0.07" rpy="0 0 0" />

    <xacro:shared_paddle_link name="right_paddle" plate_name="right_paddle_plate" parent_name="right_side" xyz="0.08 0.025 0.08" rpy="2.0 0.2 -1.8" />
    <xacro:shared_paddle_link name="left_paddle" plate_name="left_paddle_plate" parent_name="left_side" xyz="0.08 -0.025 0.08" rpy="-2.0 0.2 1.8" />

    <!-- <xacro:shared_wheel_link name="right_wheel" x_angle="${pi/2}" xyz="0.12 -0.215 0" />
    <xacro:shared_wheel_link name="left_wheel" x_angle="-${pi/2}" xyz="0.12 0.215 0" /> -->

    <xacro:shared_wheel_link name="right_wheel" x_angle="${pi/2}" xyz="0.1 -0.215 0" />
    <xacro:shared_wheel_link name="left_wheel" x_angle="-${pi/2}" xyz="0.1 0.215 0" />

</robot>